# Generated by Django 5.1.7 on 2025-04-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shelfallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('harmony', 'Harmony Search'), ('tabu', 'Tabu Search')], max_length=20)),
                ('fitness_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_log', models.TextField()),
            ],
        ),
    ]
