# Generated by Django 5.1.7 on 2025-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_optimizationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='time_taken',
            field=models.FloatField(default=0, help_text='Time in seconds'),
        ),
    ]
